### ISSUE TITLE
INA219 - Potential error in ina219_get_gain 

### ISSUE THREAD

**Issue by HarterHorst** [UncleRus/esp-idf-lib#100]
**Device type**
- [x] ESP32
- [ ] ESP8226

**Framework version**
- [x] ESP-IDF latest master
- [ ] ESP-IDF 3.2.x
- [ ] ESP-IDF 3.3.x
- [ ] ESP8266 RTOS SDK latest master
- [ ] ESP8266 RTOS SDK 3.2

**Describe the bug**
In order for the driver to work correct a calibration of the sensor is required. This is stated in the TI datasheet and mainly done via the ina219_calibrate function in ina219.c. In order to calculate the calibration values, some current values have to be read from the configuration register. This does not work for ina219_get_gain, because it delivers a negativ value. 

OK, some more details: The ina219_configure routine writes some configuration to the config register of the INA219. One of them is the PGA (programmable-gain amplifier) setting in Bit 11 and 12 aka gain. I write bin 11 to both register (which is default) and decimal 3 but the ina219_get_gain does not read the correct value. It delivery a negative value. Troubleshooting this is beyond my capabilities so I hope someone can help me here.

**Comment by UncleRus** [comment]
Thank you!
