### ISSUE TITLE
Compile error in dport_panic_highint_hdl (head version)

### ISSUE THREAD

**Issue by surfskidude** [UncleRus/esp-idf-lib#101]
I just checked out the latest head version and I get the following compile errors:

/home/develop/esp/esp-idf/components/esp_system/port/esp32/dport_panic_highint_hdl.S: Assembler messages:
/home/develop/esp/esp-idf/components/esp_system/port/esp32/dport_panic_highint_hdl.S:383: Error: invalid symbolic operand
/home/develop/esp/esp-idf/components/esp_system/port/esp32/dport_panic_highint_hdl.S:383: Error: invalid symbolic operand

**Comment by UncleRus** [comment]
It looks this is ESP-IDF error, not the esp-idf-lib.
