### ISSUE TITLE
Failed to build with size optimization enabled

### ISSUE THREAD

**Issue by fukaminakrize** [UncleRus/esp-idf-lib#103]
**Device type**
- [x] ESP32
- [x] ESP8226

**Framework version**
- [x] ESP-IDF latest master

**Describe the bug**
Hi, when building examples for components depending on i2cdev component (such as ads1115, bme680 or ds1307) with compiler's optimization level set to `-Os`, build fails with `undefined reference` errors to functions `i2c_dev_read_reg` and `i2c_dev_write_reg`. I've looked into their implementations and I suspect the problem is with the functions' inlining.  Reimplementation of them as non-inlined functions resolved the issue.

[sdkconfig.txt](https://github.com/UncleRus/esp-idf-lib/files/5052413/sdkconfig.txt)
[build_log.txt](https://github.com/UncleRus/esp-idf-lib/files/5052414/build_log.txt)

**Comment by UncleRus** [comment]
Thank you for reporting this!
