### ISSUE TITLE
ds1307: wrong squarewave frequency returned

### ISSUE THREAD

**Issue by ansemjo** [UncleRus/esp-idf-lib#110]
**Device type**
- [x] ESP32
- [ ] ESP8226

**Framework version**
- [ ] ESP-IDF latest master
- [x] ESP-IDF 4.0.1 (via PlatformIO)
- [ ] ESP-IDF 3.2.x
- [ ] ESP-IDF 3.3.x
- [ ] ESP8266 RTOS SDK latest master
- [ ] ESP8266 RTOS SDK 3.2

**Describe the bug**

When checking if RTC configuration was applied correctly, I am checking the squarewave frequency output with `ds1307_get_squarewave_freq` and comparing it against `DS1307_32768HZ`.

That check returns `false` and the returned value is `176` or `0b1011000`.

Checking against the datasheet, this is the supposed content of the control register **with the rate select bits RS0/RS1 masked out**.

In [line 191 of ds1307.c](https://github.com/UncleRus/esp-idf-lib/blob/edf9ba17056dfc376eeff31bbf105cdff407b1a6/components/ds1307/ds1307.c#L191) the returned register is `&`-ed with `SQWEF_MASK`, when it should be the inverse of that mask.

```c
#define SQWEF_MASK   0xfc
```

Changing the line to the following fixes the issue for me:

```c
*sqw_freq = val & ~SQWEF_MASK;
```

---

Another sidenote: when using this API, I am expecting to receive `true` from `ds1307_is_running` when ... well, the clock is running. However, what I am getting is the contents of the `CH` bit which stands for "clock halt". So a value of `0` actually indicates that the clock is running, which is confusing ..

**Comment by UncleRus** [comment]
Thank you!
