### ISSUE TITLE
SHT3x measurements fail after 72min

### ISSUE THREAD

**Issue by david-collett** [UncleRus/esp-idf-lib#118]
**Device type**
- [x] ESP8226

**Framework version**
- [x] ESP8266 RTOS SDK latest master

**Describe the bug**
Once the board has been running for 72min, trying to measure temp with `sht3x_measure` will fail with:

```E (4324210) SHT3x: Measurement is still running```

I believe it would fail immediately if the time was actually set. This is due to an integer overflow in the method  `get_time_us()` which returns a uint32_t which is not big enough to hold usec of more than 72min past zero.

**Comment by UncleRus** [comment]
Could you try a possible fix in #119 ?

**Comment by david-collett** [comment]
That seems to have fixed it, thanks!
