### ISSUE TITLE
pressure calculation for bme680 gives wrong results

### ISSUE THREAD

**Issue by daschr** [UncleRus/esp-idf-lib#121]
**Device type**
- [x] ESP32
- [x] ESP8226

**Framework version**
- [x] ESP-IDF latest master
- [x] ESP-IDF 3.2.x
- [x] ESP-IDF 3.3.x
- [x] ESP8266 RTOS SDK latest master
- [x] ESP8266 RTOS SDK 3.2

**Describe the bug**

I've noticed that the measured pressure is  ~20hPa higher than the real one.
After looking at [BME680_driver of BoschSensortec](https://github.com/BoschSensortec/BME680_driver/blob/9014031fa00a5cc1eea1498c4cd1f94ec4b8ab11/bme680.c#L884-L923) and  [the one of esp-idf-lib](https://github.com/UncleRus/esp-idf-lib/blob/3a96f849ec3461550cec92d03047dbe43ab8657d/components/bme680/bme680.c#L342-L371), I realised that the calculation is wrong.
After changing `bme680_convert_pressure` to the calculation used by Bosch, the values are now [right](https://wttr-beer.de/dashboard/snapshot/y5fDmHTb7Jw2LQjpPiEMVApToex74HOm?viewPanel=16&orgId=1).

**Comment by UncleRus** [comment]
Thank you!
