### ISSUE TITLE
probably text error in esp_idf_lib_helpers.h 

### ISSUE THREAD

**Issue by PaulskPt** [UncleRus/esp-idf-lib#143]
**Device type**
- [x] ESP32S2
**Framework version**
- [x] ESP-IDF-IDF blob master

**Describe the bug**
While reading the file ..UncleRus/esp-idf-lib/blob/master/components/esp_idf_lib_helpers/esp_idf_lib_helpers.h , 
I saw in line 16, the line that starts with: 
"#error BUG: ' 
at the end the text is: '&& defined (CONFIG_IDF_TARGET_ESP32S'.
I think the original text is missing a final '2' of 'ESP32S2' and a final closing bracket ')'.
So, I think this text part should read: '&& defined (CONFIG_IDF_TARGET_ESP32S2)',

Tnx for the good work!
Regards,
Paulsk (twitter @ct7agr)

**Comment by UncleRus** [comment]
Nice catch, thank you!
