### ISSUE TITLE
tca95x5.c contains pcf copy paste errors

### ISSUE THREAD

**Issue by arnoutdekimo** [UncleRus/esp-idf-lib#144]
Hi,

tca95x5.c seems to contain copy paste from the pcf857x driver for the init and freeing of the device descriptor. (e.g. pcf8574_init_desc)
Because there is no example for it, I guess you did not yet notice this.

Kind regards,
Arnout

**Comment by UncleRus** [comment]
Thank you for report!
May I ask you to help test this component on a real hardware?
