### ISSUE TITLE
HAL for SPI

### ISSUE THREAD

**Issue by UncleRus** [UncleRus/esp-idf-lib#146]
We need a library that implements a hardware abstraction layer for SPI devices, something like i2cdev.
There are a lot of good devices that we can support.

**Comment by Bytesforus** [comment]
https://github.com/loboris/ESP32_TFT_library

**Comment by UncleRus** [comment]
It looks like, unlike I2C, different devices use the SPI protocol in different ways, and it will be extremely difficult to develop and maintain a shared SPI transport library for ESP8266 and ESP32. I think it's best to leave the current approach for now: implement SPI separately for ESP8266 components only if necessary.

**Comment by UncleRus** [comment]
I'm closing this issue for now, but feel free to reopen it in case of good ideas.
