### ISSUE TITLE
(i2c_driver_delete):i2c driver install error

### ISSUE THREAD

**Issue by Albinv06** [UncleRus/esp-idf-lib#15]
Hello, 
While running the ds3231 i am getting the below error in log screen. 

components/driver/i2c.c:355 (i2c_driver_delete):i2c driver install error

What shall i need to do to fix these error? .
My IDF version : v4.0-dev-459-gba1ff1692-dirty

**Comment by UncleRus** [comment]
It's not an error. This message is displayed when the driver is first initialized. You can safely ignore it.
