### ISSUE TITLE
Support for tgsong / amazon-freertos-examples  FreeRTOS AWS ESP32 

### ISSUE THREAD

**Issue by Yoimer** [UncleRus/esp-idf-lib#164]
@UncleRus Hello. Amazing piece of work you've made. Congratulations. Is there any way your set of libraries could be implemented on this project [tgsong](https://github.com/tgsong/amazon-freertos-examples). Looking forward to hearing your comments. Thanks in advance.

**Comment by UncleRus** [comment]
Sorry, I don't understand the question. Do you want to use esp-idf-lib in your examples? Of course, you can do this, just add it as a submodule to your repository and use it as written in README.

**Comment by mbuckaway** [comment]
I'll add my two cents. I use the ESP AWS MQTT lib from Espressif to connect to my ESP32 devices to the AWS IoT Core. Espressif has done all the hard work of porting the AWS lib for you. No need to fight with Amazon's version of FreeTOS. THis allows you to make easy use of the ESP-IDF-LIB or any other ESP-IDF component. See the Espressif Github for details.

**Comment by Yoimer** [comment]
@UncleRus @mbuckaway Thanks for replying.

So @UncleRus. I was able to use your DHT library in my current AWS FreeRTOS ESP32 project (not an easy task due to AWS way to configure FreeRTOS)

@mbuckaway It's imperative to me using AWS FreeRTOS ESP32

**Comment by UncleRus** [comment]
I’m very sorry, but unfortunately I don’t plan to support AWS FreeRTOS. However, I will be happy if you implement this support.

**Comment by Yoimer** [comment]
@UncleRus Hello there. I was able to implement only the `DHT11` library. Even in the very native .zip file for `FreeRTOS V202012.00`. The rest of the libraries, I could not.
