### ISSUE TITLE
Please remove all locks

### ISSUE THREAD

**Issue by axelriet** [UncleRus/esp-idf-lib#175]
First, thanks for the library, this is a tremendous contribution!

My remark is made from a narrow point of view, which is the mcp960x I2C device driver in your library, but I suspect it may bay an instance of a systemic issue. 

I see your library attempts to be "thread safe" by taking a lock on the port and also a lock on the device when communicating. This library is not the place to take locks, really. Synchronization is best left to the callers.

As an example, I see you take both the device and port lock when clearing the interrupt in mcp960x_clear_alert_int()

Interrupts, by nature, happen at arbitrary points. If any piece of code using your library is anywhere inside any of your I2C functions talking to any device at interrupt time, clearing the interrupt from the ISR is guarantee to deadlock as the interrupted code will never release the locks.

My call is not to fix that particular spot, but to remove any and all attempts at synchronization from your library altogether.

Just zap all the mutexes and semaphores and associated code from I2C (and potentially other places where you attempt the same effort). Your library does a great job simplifying device access and should stick to that. Taking locks introduces behavioral changes and side effects that have consequences on the whole system.

**Comment by UncleRus** [comment]
First, I must apologize to you.
In many ways, you are right and I added a special CONFIG_I2CDEV_NOLOCK option to the ic2dev setting. The corresponding changes have already been pushed to the master branch.

**Comment by UncleRus** [comment]
Could you test it?

**Comment by UncleRus** [comment]
cf5d0bf I hope this satisfies you.
Closing this issue, feel fre to reopen it.
