### ISSUE TITLE
Implement lint workflow in CI

### ISSUE THREAD

**Issue by trombik** [UncleRus/esp-idf-lib#184]
**Device type**
N/A

**Framework version**
N/A

**Describe the bug**

At the moment, we do not lint the source code. `.astylerc` is in the repository, but not enforced. as a result, new code that violates the style keeps flowing in. we should test new code with a linting program, and enforce the style while old code remains as-is.

**Comment by UncleRus** [comment]
Totally agreed.
Also we need to describe the rules of contributing (how to add examples, support of older ESP-IDF versions, documenting etc).
