### ISSUE TITLE
enable "Require branches to be up to date before merging"

### ISSUE THREAD

**Issue by trombik** [UncleRus/esp-idf-lib#198]
**Device type**:

N/A

**Framework version**:

N/A

**Describe the bug**:

currently, Pull Request can be merged as long as the changes have no conflict. however, Pull Request should be tested with the latest code. "Require branches to be up to date before merging" option in GitHub repository enforces the rule.

to enable the rule, visit `Settings` > `Branches`, and click `Add rule` in `Branch protection rules`. type `master` in `Branch name pattern`. tick `Require status checks to pass before merging`, and `Require branches to be up to date before merging`. tick `All build` from the list of `Status checks found in the last week for this repository`.

**Comment by UncleRus** [comment]
Sorry, but no.
There are only two of us, who can directly push to master and I am sure that we are smart enough to use this opportunity wisely.
