### ISSUE TITLE
CO2 Sensor SCD4x 

### ISSUE THREAD

**Issue by SERIDJ** [UncleRus/esp-idf-lib#204]
I am requesting a driver for `SCD4x`.

### Device description

The SCD4x is Sensirion’s next generation miniature CO2 sensor that offers an unmatched price-to-performance ratio. Tape and reel packaging combined with its SMD assembly processing make the SCD4x ideal for high-volume application

`SCD4x` is a chip to do a great thing. It supports only I2C. It
supports VDD from 2.4V to 5.5V. Output range: 0 to 40’000 ppm 

### Device information

 data sheet 
https://www.sensirion.com/fileadmin/user_upload/customers/sensirion/Dokumente/9.5_CO2/Sensirion_CO2_Sensors_SCD4x_Datasheet.pdf

The product information and the data sheet can be found at:

https://www.sensirion.com/en/environmental-sensors/carbon-dioxide-sensors/carbon-dioxide-sensor-scd4x/

### Purchasing the product

The device can be purchased at:

- [x] Digi-Key

The URLs where you can buy the device are:

- https://www.digikey.fr/product-detail/fr/sensirion-ag/SCD40-D-R2/1649-SCD40-D-R2CT-ND/13684008
- https://www.digikey.fr/products/fr?keywords=SCD4x

### Other implementation

There is a driver for Arduino at : https://github.com/Sensirion/arduino-i2c-scd4x
and for Rasbery at : https://github.com/Sensirion/raspberry-pi-i2c-scd4x

**Comment by UncleRus** [comment]
Please help me with testing and developing example here #209
