### ISSUE TITLE
AHT driver has a bug

### ISSUE THREAD

**Issue by MarkEvens** [UncleRus/esp-idf-lib#222]
**Device type**:

- [x] ESP32

**Framework version**:

- [x] ESP-IDF 4.2.1

**Describe the bug**:
I just running your example I it is giving timeout error

```
 (0) cpu_start: Starting scheduler on APP CPU.
E (220) i2cdev: Could not write to device [0x38 at 0]: 263
ESP_ERROR_CHECK failed: esp_err_t 0x107 (ESP_ERR_TIMEOUT) at 0x400d1d44
0x400d1d44: _esp_error_check_failed at /home/***/esp/esp-idf/components/esp_common/src/esp_err.c:45

func: void task(void*)
expression: aht_init(&dev)
```

**Comment by UncleRus** [comment]
First, you have to write what type of AHT chip you use: is this AHT10 or AHT15 or maybe AHT20?
Second, bug is not confirmed. I just tested example on a real device:
```
...
I (283) heap_init: At 4008BFC8 len 00014038 (80 KiB): IRAM
I (289) spi_flash: detected chip: generic
I (294) spi_flash: flash io: qio
I (298) cpu_start: Starting scheduler on PRO CPU.
I (0) cpu_start: Starting scheduler on APP CPU.
I (350) aht-example: Sensor calibrated
I (430) aht-example: Temperature: 24.2°C, Humidity: 30.56%
I (1010) aht-example: Temperature: 24.2°C, Humidity: 30.51%
I (1590) aht-example: Temperature: 24.2°C, Humidity: 30.48%
I (2170) aht-example: Temperature: 24.2°C, Humidity: 30.46%
I (2750) aht-example: Temperature: 24.2°C, Humidity: 30.42%
I (3330) aht-example: Temperature: 24.2°C, Humidity: 30.41%
...
```
Recheck your wiring. 
- Is the AHT receiving power?
- Are the SDA and SCL lines connected correctly?
- Are proper pull-up resistors connected to the SDA and SCL lines?
- AHT has two possible I2C addresses, 0x38 (AHT_I2C_ADDRESS_GND) is used by default in the example. Perhaps in your circuit the ADR pin of AHT is connected not to ground but to + 3.3V? In this case, the address will be different.

And please read the FAQ.
