### ISSUE TITLE
max31855

### ISSUE THREAD

**Issue by casey-zebrowski** [UncleRus/esp-idf-lib#245]
I am requesting a driver for `MAX31855`.

### Device description

The MAX31855 performs cold-junction compensation and digitizes the signal from a K-, J-, N-, T-, S-, R-, or
E-type thermocouple. The data is output in a signed 14-bit, SPI-compatible, read-only format. This converter
resolves temperatures to 0.25°C, allows readings as high as +1800°C and as low as -270°C, and exhibits
thermocouple accuracy of ±2°C for temperatures ranging from -200°C to +700°C for K-type thermocouples.

### Device information

The product information and the data sheet can be found at:
https://www.maximintegrated.com/en/products/interface/sensor-interface/MAX31855.html

https://datasheets.maximintegrated.com/en/ds/MAX31855.pdf

### Purchasing the product

The device can be purchased at:

- [x] Aliexpress
- [ ] Amazon
- [ ] ebay
- [x] Digi-Key
- [x] Mouser

The URLs where you can buy the device are:

- https://www.digikey.com/en/products/base-product/maxim-integrated/175/MAX31855/82847
- https://www.mouser.com/new/maxim-integrated/maximmax31855/

### Other implementation

There is a driver for MAX31855 at https://github.com/adafruit/Adafruit-MAX31855-library

**Comment by UncleRus** [comment]
Please test #324
