### ISSUE TITLE
PCF8563 library

### ISSUE THREAD

**Issue by gheuser** [UncleRus/esp-idf-lib#250]
**Device type**:

- [x] ESP32

**Framework version**:

- [x] ESP-IDF 4.3
- [x] ESP-IDF 3.3.x

**Describe the bug**:

https://github.com/UncleRus/esp-idf-lib/blob/master/components/pcf8563/pcf8563.c 
_pcf8563_set_time_ line 157
_pcf8563_get_time_ line 180

According to the PCF8563 datasheet register table (Table 4 - link below), the date sequence is: monthDays at address 0x05 and weekDays at address 0x06, but after acquiring data from I2C, in function _pcf8563_get_time_ the, struct time.tm_wday receives Days and time.tm_mday receives weekDays. (same to _pcf8563_set_time_)

Furthermore datasheet Table 4 says: "_Bit positions labelled as x are not relevant._" and reading this bits I realized that sometimes they change.. because of this I beleave a mask is needed:

    *valid = data[0] & BV(BIT_VL) ? false : true;
    time->tm_sec = bcd2dec(data[0] & ~BV(BIT_VL));
    time->tm_min = bcd2dec(data[1] & 0x7F);
    time->tm_hour = bcd2dec(data[2] & 0x3F);
    time->tm_mday = bcd2dec(data[3] & 0x3F);
    time->tm_wday = bcd2dec(data[4] & 0x7);
    time->tm_mon = bcd2dec(data[5] &  0x1F & ~BV(BIT_YEAR_CENTURY)) - 1;
    time->tm_year = bcd2dec(data[6]) + (data[5] & BV(BIT_YEAR_CENTURY) ? 200 : 100);

https://www.nxp.com/docs/en/data-sheet/PCF8563.pdf - item 8.2, page 6

**Comment by UncleRus** [comment]
Thank you for testing and reporting!
