### ISSUE TITLE
CI: "Invalid certificate" error

### ISSUE THREAD

**Issue by UncleRus** [UncleRus/esp-idf-lib#251]
CI build for esp-idf v4.x fails with error
> gen_crt_bundle.py: Invalid certificate in /home/runner/work/esp-idf-lib/esp-idf-lib/idf/components/mbedtls/esp_crt_bundle/cacrt_all.pem

See https://github.com/UncleRus/esp-idf-lib/runs/3765359930

@trombik Could you take a look at this?

**Comment by trombik** [comment]
ack

**Comment by limpens** [comment]
Have a look at this: https://github.com/espressif/esp-idf/issues/7621#issuecomment-932070666

It looks like the issue is concentrating around the expired "DST Root CA X3", but the culprit looks to be the EC-ACC certificate.

Hope this helps.

**Comment by trombik** [comment]
probably, disabling CONFIG_MBEDTLS_CERTIFICATE_BUNDLE should work, but I'm wondering how the upstream resolve the issue.

**Comment by trombik** [comment]
updates from the upstream:

https://github.com/espressif/esp-idf/issues/7631#issuecomment-934212224
