### ISSUE TITLE
I2C Frequency Setting for BME680 Driver

### ISSUE THREAD

**Issue by tllaughn** [UncleRus/esp-idf-lib#265]
In the components/bme680/bme680.c file, the frequency is defined as 
#define I2C_FREQ_HZ 1000000 // Up to 3.4MHz, but esp-idf only supports 1MHz

However, for the ESP32C3 (and perhaps other platforms), the frequency should only be 100kHz.
#define I2C_FREQ_HZ 100000 // Up to 3.4MHz, but esp-idf only supports 1MHz

**Comment by UncleRus** [comment]
Yes, I suppose it would be nice to limit the default frequency for different platforms.

But for now you easily can set whichever I2C clock you want [FAQ](https://github.com/UncleRus/esp-idf-lib/blob/master/FAQ.md#how-can-i-change-frequency-of-i2c-clock-at-default-frequency-my-device-is-unstable-or-not-working-at-all).

**Comment by tllaughn** [comment]
Awesome!  Thanks.

Sent from my iPad.
Please forgive any typos or autocorrections!
-Theo

On Nov 28, 2021, at 5:43 AM, Ruslan V. Uss ***@***.***> wrote:

﻿

Yes, I suppose it would be nice to limit the default frequency for different platforms.

But for now you easily can set whichever I2C clock you want FAQ<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FUncleRus%2Fesp-idf-lib%2Fblob%2Fmaster%2FFAQ.md%23how-can-i-change-frequency-of-i2c-clock-at-default-frequency-my-device-is-unstable-or-not-working-at-all&data=04%7C01%7C%7C23b0e0ce80224730661a08d9b25bebeb%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637736930139788467%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=jM2F%2Fp2W78Gph%2Fjmz9Z8vivhpySOgPAt5SSoKs3r0Ps%3D&reserved=0>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FUncleRus%2Fesp-idf-lib%2Fissues%2F265%23issuecomment-981062075&data=04%7C01%7C%7C23b0e0ce80224730661a08d9b25bebeb%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637736930139788467%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Oin%2Bw4NlfvZhqh0%2BNGEsWtrrGcYbgLAeK7D21oA0teo%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABVHNMDNUAI7OUA4JORLYVTUOIBVHANCNFSM5IRKZE4Q&data=04%7C01%7C%7C23b0e0ce80224730661a08d9b25bebeb%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637736930139788467%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=HfN539jXJ2PIgESHXRNwmSam6ONRvpBnJCLmF1zX7UM%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C23b0e0ce80224730661a08d9b25bebeb%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637736930139798415%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=POb4e%2FV%2F2%2FAWVEhvwYxBeSAALfmp0Zeo6th%2B36iSWeU%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C23b0e0ce80224730661a08d9b25bebeb%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637736930139798415%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=DarouXmll5LUhy%2BzlzJ1Dw5IPNfgFz%2Fd7PuFkmIZETU%3D&reserved=0>.

**Comment by trombik** [comment]
@tllaughn are you sure the max frequency for esp32c3 is 100 Khz? the doc says it supports 1 Mhz at least, and 2 Mhz with `XTAL` as clock source.

https://docs.espressif.com/projects/esp-idf/en/latest/esp32c3/api-reference/peripherals/i2c.html

**Comment by trombik** [comment]
i also thought per-device-per-target `I2C_FREQ_HZ` would be nice to have, but max frequency depends on device, target, _and_ clock source. that means it depends on how users use the target. as the FAQ suggests, you should change the frequency in your code.

changing the default to the fastest frequency for all targets is another idea, but I'm not sure.
