### ISSUE TITLE
Can control a strip Led SK6812 RGB with 1 wire?

### ISSUE THREAD

**Issue by LeonardoZambonelliAxel** [UncleRus/esp-idf-lib#268]
Hi, 
can your led_strip library control a SK6812 RGB strip with just 1 wire?

**Comment by UncleRus** [comment]
I don't quite understand what is causing your question, but yes, the driver does support SK6812. 

To test it, connect the DIN of the first LED in strip to GPIO 5 and edit line 6 of main.c in the example:

```C
#define LED_TYPE LED_STRIP_SK6812
```

Then build and flash example to your ESP32.
