### ISSUE TITLE
pointer error in sht4x example

### ISSUE THREAD

**Issue by pinchy** [UncleRus/esp-idf-lib#269]
**Describe the bug**:

incompatible type error in [examples/sht4x/main/main.c](https://github.com/UncleRus/esp-idf-lib/blob/master/examples/sht4x/main/main.c) line 58.

`uint8_t duration = sht4x_get_measurement_duration(dev);`

should read
    
   
`uint8_t duration = sht4x_get_measurement_duration(&dev);`

**Comment by UncleRus** [comment]
Thank you!
