### ISSUE TITLE
I always get reset when using i2c libraries like sht3x, sht4x, aht...

### ISSUE THREAD

**Issue by hoatenhu** [UncleRus/esp-idf-lib#273]
**Device type**:

- [x] ESP32

**Framework version**:

- [x] ESP-IDF 4.1

**Describe the bug**:

Here is my log, 

my chip is reset all the time (esp32-wroom-32)

![image](https://user-images.githubusercontent.com/84147184/147390291-2d1d2829-4f1e-4a49-af18-e890ddf9b31a.png)

**Comment by hoatenhu** [comment]
when i remove ESP-ERR-CHECK in my code it gives this error

![image](https://user-images.githubusercontent.com/84147184/147390576-f0a9039c-72f7-4fd4-b9b9-33d71fc3cc2f.png)

**Comment by UncleRus** [comment]
Please read the FAQ:
https://github.com/UncleRus/esp-idf-lib/blob/master/FAQ.md#how-to-debug-i2c-based-drivers
This is I2C scanner:
https://github.com/UncleRus/esp-idf-i2cscan

PS I kindly ask you not to use images when you post logs. Use markdown instead.
