### ISSUE TITLE
Example for mcp23x17

### ISSUE THREAD

**Issue by aeropagz** [UncleRus/esp-idf-lib#287]
Hello UncleRus,

I am quite new to the esp-idf universe and I need to work with a port expander. I found ur mcp23x17 lib and your documentation on espressif docs but I am still clueless how to use ur lib. Could you link/give an example usage please?

Would be super helpful!

Best regards

Klaas

**Comment by UncleRus** [comment]
All examples are available in [examples](/UncleRus/esp-idf-lib/tree/master/examples) directory.

**Comment by aeropagz** [comment]
Ah nice thank you very much! Maybe it would be nice to link them in the espressiv documentation.
