### ISSUE TITLE
i2c timing value error

### ISSUE THREAD

**Issue by AlwinvanderPal** [UncleRus/esp-idf-lib#303]
### The issue

I'm trying to use the SHT3x and SCD4x library's. Which builds correct. 
After flashing the ESP_ERROR_CHECK gives an I2C set timeout error. This happens after I2C is initialized and the correct GPIO are selected with sht3x_init_desc and scd4x_init_desc. 
After that the next line generated the error: E (302) i2c: i2c_set_timeout(817): i2c timing value error. In case of sht3x this is function sht3x_init and with scd4x this is scd4x_wake_up (i couldn't find this function in the datasheet and after removing it the next line generated the same error "scd4x_stop_periodic_measurement"). 
I used the FetchContent method to add the component path which added the components to the build map. 

### Which SDK are you using?

esp-idf

### Which version of SDK are you using?

4.4

### Which build target have you used?

- [ ] esp32
- [ ] esp32s2
- [X] esp32s3
- [ ] esp32c2
- [ ] esp8266
- [ ] other

### Component causing the issue

SHT3x

### Anything in the logs that might be useful for us?

```console
I (0) cpu_start: Starting scheduler on APP CPU.
E (302) i2c: i2c_set_timeout(817): i2c timing value error
ESP_ERROR_CHECK failed: esp_err_t 0x102 (ESP_ERR_INVALID_ARG) at 0x4037a0ac
0x4037a0ac: _esp_error_check_failed at C:/Users/alwin/esp/esp-idf/components/esp_system/esp_err.c:42

file: "../main/main.c" line 149
func: app_main
expression: sht3x_init(&dev)

abort() was called at PC 0x4037a0af on core 0
```

### Additional information or context

Reading with Arduino works fine.
Salea logic analyser doesn't detect anything on the bus. 

### Confirmation

- [X] This report is not a question nor a request for drivers.

**Comment by UncleRus** [comment]
Thank you for reporting!
