### ISSUE TITLE
update v4.2.x branch in CI to v4.2.3

### ISSUE THREAD

**Issue by trombik** [UncleRus/esp-idf-lib#310]
### The issue

the 4.2.x branch in CI is currently v4.2.2. `esp-idf` v4.2.3 has been released.

### The context

https://github.com/espressif/esp-idf/releases/tag/v4.2.3

### Possible solution

update the version in the GitHub Actions workflow.

### Confirmation

- [X] This report is not a bug report in code, a question, nor a request for drivers.

**Comment by UncleRus** [comment]
Thank you!
