### ISSUE TITLE
A I2C Bug

### ISSUE THREAD

**Issue by lpitt10** [UncleRus/esp-idf-lib#330]
### The issue

There is "definition i2c_dev_t" in esp-idf now, and there is "definition i2c_dev_t" too in esp-idf-lib now.
so i2c don't work.

### Which SDK are you using?

esp-idf

### Which version of SDK are you using?

V4.4.1

### Which build target have you used?

- [ ] esp32
- [ ] esp32s2
- [ ] esp32s3
- [X] esp32c2
- [ ] esp8266
- [ ] other

### Component causing the issue

i2c don't work

### Anything in the logs that might be useful for us?

```console
sed -i "s/i2c_dev_t/i2c_device_t/g" `grep i2c_dev_t -rl ./esp-idf-lib`
```

### Confirmation

- [X] This report is not a question nor a request for drivers.

**Comment by UncleRus** [comment]
The definition of `i2c_dev_t` has been in ESP-IDF for a long time. Since it is used in low-level SoC definitions, and these low-level headers must be included for conflict, this is not a problem.
