### ISSUE TITLE
CI: e-mails from github "Run failed at startup"

### ISSUE THREAD

**Issue by UncleRus** [UncleRus/esp-idf-lib#407]
### The issue

For every PR created, I immediately get messages like this:
![изображение](https://user-images.githubusercontent.com/533006/176797033-94cf58fa-ae91-4843-bab7-b47baf4c2c98.png)

### Confirmation

- [X] This report is not a bug report in code, a question, nor a request for drivers.

**Comment by trombik** [comment]
its still failing for another bug.

**Comment by trombik** [comment]
fixed in #411
