### ISSUE TITLE
Driver for MAX1704X series battery fuel gauge

### ISSUE THREAD

**Issue by shuki25** [UncleRus/esp-idf-lib#416]
### Device name

MAX1704X

### Device description

The  MAX17043/MAX17044 and MAX17048/MAX17049  are  ultra-compact,  low-cost, host-side fuel-gauge systems for lithium-ion (Li+) batteries in handheld and portable equipment. The MAX17043/MAX17048 is configured to operate with a single lithium cell and the MAX17044/MAX17049 is configured for a dual-cell 2S pack.

MAX17048/MAX17049 has more features than the predecessor chip which supports alert status, threshold for alert, etc. 

It uses I2C to read and write data. It provides battery voltage, state of charge (battery life, like a fuel gauge) and rate of change (either charging to full or discharging to empty).

### Device product page URL

https://www.maximintegrated.com/en/products/power/battery-management/MAX17048.html

### Datasheet URL

https://datasheets.maximintegrated.com/en/ds/MAX17048-MAX17049.pdf

### Can the device be purchased at any of the followings?

- [X] AliExpress
- [X] Amazon
- [X] ebay
- [X] Digi-Key
- [X] Mouser

### URLs to purchase the device

https://www.mouser.com/ProductDetail/Maxim-Integrated/MAX17048G%2bT10?qs=D7PJwyCwLAoGnnn8jEPRBQ%3D%3D
https://www.digikey.com/en/products/detail/analog-devices-inc-maxim-integrated/MAX17048G-T10/3758921

Breakout board:
https://www.amazon.com/HiLetgo-MAX17043-Lithium-Battery-Converter/dp/B01NBE99EP/ref=sr_1_2?crid=NGPG2VQ8237S

### Other implementations

I am contributing the driver for this device.  There are two devices (MAX17043/17044 and MAX17048/17049) and I'm writing one driver that supports both.  The latter has more features.

https://github.com/shuki25/esp-idf-lib/tree/feature-max1704x

Expect pull request anytime soon in the next week or two.

**Comment by shuki25** [comment]
Contribution instructions say assign this issue to myself, I see a way to do it...

**Comment by trombik** [comment]
@shuki25 you are correct. the CONTRIBUTING.md is wrong. you don't have to assign yourself to the issue.

recently, we are changing the workflow. there might be inconsistencies in the documentation. if you have a question, feel free to ask here.

**Comment by shuki25** [comment]
@trombik Thanks. I do have a question, I'm using VS Code as an IDE, I'm trying to set up clang-format to follow LLVM style and I couldn't get it to working right.  Is there a .clang-format file for the project that I can use?

**Comment by UncleRus** [comment]
> @trombik Thanks. I do have a question, I'm using VS Code as an IDE, I'm trying to set up clang-format to follow LLVM style and I couldn't get it to working right. Is there a .clang-format file for the project that I can use?

`.clang-format` added in #421

**Comment by roblatour** [comment]
Is this still active?

**Comment by shuki25** [comment]
> Is this still active?

I have source code written up for my other firmware project. Work and life has taken over my free time.  Haven't had a chance to finish up writing all functions for that particular chip.  I'm an instructor at an University, my summer break starts in a couple weeks.  By then, I will finish it up and clean it up for the pull request.

**Comment by roblatour** [comment]
I hear you brother :-)  Thanks for the effort your putting into it!
