### ISSUE TITLE
DS18X20_ANY causes incorrect temperature in single sensor example code.

### ISSUE THREAD

**Issue by AndyChessum** [UncleRus/esp-idf-lib#434]
### The issue

Hi,

I tried both the multi and single example code in PlatformIO with a single DS18B20 sensor.  The multi example worked fine, but the single example reported a temperature of 204 degrees.  When I replaced DS18X20_ANY with the actual address of the sensor, the correct temperature was reported.

I have tried different sensors (always one at a time) and am using an external 4.7K resistor, as suggested.

### Which SDK are you using?

esp-idf

### Which version of SDK are you using?

master

### Which build target have you used?

- [X] esp32
- [ ] esp32s2
- [ ] esp32s3
- [ ] esp32c2
- [ ] esp8266
- [ ] other

### Component causing the issue

DS18x20

### Anything in the logs that might be useful for us?

```console
2mI (297) cpu_start: Starting scheduler on PRO CPU.␛[0m
␛[0;32mI (0) cpu_start: Starting scheduler on APP CPU.␛[0m
␛[0;32mI (1808) ds18x20_test: Sensor : 204.44°C␛[0m
Temperature 204.437500␛[0;32mI (3558) ds18x20_test: Sensor : 204.44°C␛[0m
Temperature 204.437500␛[0;32mI (5308) ds18x20_test: Sensor : 204.44°C␛[0m
Temperature 204.437500␛[0;32mI (7058) ds18x20_test: Sensor : 204.44°C␛[0m
Temperature 204.437500␛[0;32mI (8808) ds18x20_test: Sensor : 204.44°C␛[0m
```

### Additional information or context

erbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/nodemcu-32s.html
PLATFORM: Espressif 32 (5.0.0) > NodeMCU-32S
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
DEBUG: Current (cmsis-dap) External (cmsis-dap, esp-bridge, esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
PACKAGES: 
 - framework-espidf @ 3.40401.0 (4.4.1) 
 - tool-cmake @ 3.16.4 
 - tool-esptoolpy @ 1.30300.0 (3.3.0) 
 - tool-ninja @ 1.9.0 
 - toolchain-esp32ulp @ 1.22851.191205 (2.28.51) 
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch3
Reading CMake configuration...
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 74 compatible libraries
Scanning dependencies...
Dependency Graph
|-- ds18x20
|   |-- onewire
|   |   |-- esp_idf_lib_helpers
|   |-- esp_idf_lib_helpers
Building in release mode
Compiling .pio/build/nodemcu-32s/src/main.o
Linking .pio/build/nodemcu-32s/firmware.elf
Retrieving maximum program size .pio/build/nodemcu-32s/firmware.elf
Checking size .pio/build/nodemcu-32s/firmware.elf
Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
RAM:   [          ]   3.5% (used 11380 bytes from 327680 bytes)
Flash: [==        ]  17.0% (used 177781 bytes from 1048576 bytes)
Building .pio/build/nodemcu-32s/firmware.bin
esptool.py v3.3
Creating esp32 image...
Merged 2 ELF sections
Successfully created esp32 image.

### Confirmation

- [X] This report is not a question nor a request for drivers.

**Comment by UncleRus** [comment]
I apologize for the delay in reply.

This happens because the function that calculates the measured temperature (`esp_err_t ds18x20_read_temperature(gpio_num_t pin, ds18x20_addr_t addr, float *temperature)`)
cannot understand which family the sensor belongs to (because of DS18X20_ANY instead of address). In this case please use an explicit read/measure function, i.e. change the example, instead of:
```C
res = ds18x20_measure_and_read(SENSOR_GPIO, SENSOR_ADDR, &temperature);
```
use
```C
res = ds18b20_measure_and_read(SENSOR_GPIO, SENSOR_ADDR, &temperature);
```

I made changes to the driver and now in this case (impossibility to determine the sensor family) it will give an error.
