### ISSUE TITLE
Driver for DPS310 using I2C

### ISSUE THREAD

**Issue by beriberikix** [UncleRus/esp-idf-lib#456]
### Device name

DPS310

### Device description

DPS310 is a Precision Barometric Pressure / Altitude Sensor.

### Device product page URL

https://www.infineon.com/cms/en/product/sensor/pressure-sensors/pressure-sensors-for-iot/dps310/

### Datasheet URL

https://www.infineon.com/dgdl/Infineon-DPS310-DataSheet-v01_02-EN.pdf?fileId=5546d462576f34750157750826c42242

### Can the device be purchased at any of the followings?

- [ ] AliExpress
- [X] Amazon
- [ ] ebay
- [X] Digi-Key
- [ ] Mouser

### URLs to purchase the device

https://www.amazon.com/Adafruit-Precision-Barometric-Pressure-Altitude/dp/B084HLY683/ref=sr_1_1?
https://www.digikey.com/en/products/detail/seeed-technology-co-ltd/101020812/11506698

### Other implementations

https://www.arduino.cc/reference/en/libraries/adafruit-dps310/
https://adafruit.github.io/Adafruit_DPS310/html/class_adafruit___d_p_s310.html
https://github.com/adafruit/Adafruit_CircuitPython_DPS310

**Comment by keenanjohnson** [comment]
+1

**Comment by trombik** [comment]
DPS310 is not easy to source (i'm in a country where sources are severely limited). you have two options:

1. port existing driver (assuming it's an I2C device, it should not be difficult. use `i2cdev` component)
2. send me sample boards

**Comment by trombik** [comment]
@beriberikix you may contact me at https://t.me/mkrsgh for shipping details.

**Comment by keenanjohnson** [comment]
I also have hardware available here and I'm open to testing code on my hardware if that helps out at all!

**Comment by trombik** [comment]
@beriberikix you may try the alpha version at #463 . it does not implement background mode, yet (no convenient function to start and read in background). however, all the necessary bits are in the driver. I'll be away from keyboard on the weekend.

**Comment by trombik** [comment]
fixed in #463

**Comment by keenanjohnson** [comment]
FYI I have confirmed that this is working with my sensor here. See it in action: https://github.com/Ribbit-Network/ribbit-network-frog-sensor/pull/185

Thanks all!
