### ISSUE TITLE
Possible bug in max7219 LED driver

### ISSUE THREAD

**Issue by iliasam** [UncleRus/esp-idf-lib#470]
### The issue

I meet a problem with max7219 driver when I was using it with 7-segment display: 
max7219_draw_text_7seg() function is not detecting zero bytes in null-terminated input string, which causes drawing wrong (not expected) symbols after good ones.

I checked the code of max7219_draw_text_7seg() function, and I think that there is a bug at 239 line of the driver:  
  [ while (s && pos < dev->digits)](https://github.com/UncleRus/esp-idf-lib/blob/5008419d18e0ab8b1d089629b7708d4debfa1636/components/max7219/max7219.c#L239)
As I can understand from the code, the idea was to check that current symbol of the string is not null, null symbol stops drawing.
But "s" is a pointer (address in memory), so it is not null and it should not became null.
Changing this line to "while (*s && (pos < dev->digits))" is making this code sensitive to null-terminated strings and resolve the problem.

### Which SDK are you using?

esp-idf

### Which version of SDK are you using?

v4.4.2

### Which build target have you used?

- [X] esp32
- [ ] esp32s2
- [ ] esp32s3
- [ ] esp32c2
- [ ] esp8266
- [ ] other

### Component causing the issue

MAX7219

### Confirmation

- [X] This report is not a question nor a request for drivers.

**Comment by UncleRus** [comment]
Thank you!
