### ISSUE TITLE
HMC5883L values stuck at 0

### ISSUE THREAD

**Issue by laukik-hase** [UncleRus/esp-idf-lib#48]
When executed for the HMC5883L, the following is generated:

components/driver/i2c.c:353 (i2c_driver_delete):i2c driver install error

Magnetic data: X:0.00 mG, Y:0.00 mG, Z:0.00 mG
Magnetic data: X:0.00 mG, Y:0.00 mG, Z:0.00 mG
Magnetic data: X:0.00 mG, Y:0.00 mG, Z:0.00 mG

I checked the sensor with an Arduino UNO, it works fine. What can be the issue?

**Comment by UncleRus** [comment]
> i2c driver install error: 
This is not an error, you can safely ignore this message.

Just test again with latest ESP-IDF master:
```
W (289) cpu_start: Chip revision is higher than the one configured in menuconfig. Suggest to upgrade it.
I (300) cpu_start: Starting scheduler on PRO CPU.
I (0) cpu_start: Starting scheduler on APP CPU.
E (0) i2c: /home/rus/work/esp/esp32/esp-idf/components/driver/i2c.c:353 (i2c_driver_delete):i2c driver install error
Magnetic data: X:92.92 mG, Y:10.12 mG, Z:-557.52 mG
Magnetic data: X:98.44 mG, Y:11.96 mG, Z:-557.52 mG
Magnetic data: X:94.76 mG, Y:11.96 mG, Z:-558.44 mG
Magnetic data: X:96.60 mG, Y:12.88 mG, Z:-555.68 mG
Magnetic data: X:99.36 mG, Y:10.12 mG, Z:-556.60 mG
Magnetic data: X:97.52 mG, Y:11.96 mG, Z:-555.68 mG
Magnetic data: X:98.44 mG, Y:13.80 mG, Z:-557.52 mG
Magnetic data: X:97.52 mG, Y:11.96 mG, Z:-555.68 mG
Magnetic data: X:98.44 mG, Y:13.80 mG, Z:-554.76 mG
Magnetic data: X:97.52 mG, Y:11.96 mG, Z:-554.76 mG
```
Please check sensor connectivity and pull-up resistors on I2C line.
