### ISSUE TITLE
request - PCF8575 example use of specific pin

### ISSUE THREAD

**Issue by TalSomech** [UncleRus/esp-idf-lib#495]
### The issue

Hi im currently using PFC8575TS and i wanted to use your library to make it easier to write and read from the IO expander 
but i've not seen if possible a way to write to a specific pin inside the IO expander and would like an example if possible , if not if you could make me understand , since in the docs all that is written refers to address or descriptor.

### Which SDK are you using?

esp-idf

### Which version of SDK are you using?

latest

### Which build target have you used?

- [ ] esp32
- [ ] esp32s2
- [X] esp32s3
- [ ] esp32c2
- [ ] esp8266
- [ ] other

### Component causing the issue

switch

### Confirmation

- [X] This report is not a question nor a request for drivers.

**Comment by trombik** [comment]
Here is the example: https://github.com/UncleRus/esp-idf-lib/tree/master/examples/pcf8575/default

If you don't understand it, use the forum instead of Issues.
