### ISSUE TITLE
SGM58031 driver

### ISSUE THREAD

**Issue by jmpmscorp** [UncleRus/esp-idf-lib#510]
### Device name

SGM58031

### Device description

SMG58031 is a 16-bit, 4 multiplexed inputs, delta-sigma ADC. SGM58031 is ADS111x full compatible but it has different data rates and add more configuration options.

### Device product page URL

https://www.sg-micro.com/show-product-812.html

### Datasheet URL

https://www.sg-micro.com/uploads/soft/20220609/1654744052.pdf

### Can the device be purchased at any of the followings?

- [X] AliExpress
- [X] Amazon
- [ ] ebay
- [ ] Digi-Key
- [ ] Mouser

### URLs to purchase the device

https://es.aliexpress.com/i/1005004879391158.html

**Comment by jmpmscorp** [comment]
I have added this new driver on my fork, branch feat-sgm58031.
[https://github.com/jmpmscorp/esp-idf-lib/tree/feat-sgm58031](url)

Check it and if all is ok, I'll send PR.

**Comment by trombik** [comment]
Please create a PR. Otherwise, the CI wouldn't run.
