### ISSUE TITLE
Error 'Could not take device mutex' in BME680 example

### ISSUE THREAD

**Issue by alafi** [UncleRus/esp-idf-lib#52]
**Devcie type**
- [x] ESP32

**Framework version**
- [x] ESP-IDF latest master

**Describe the bug**
Error in executing the BME680 example:
`I2C_DEV: [0x77 at 0] Could not take device mutex`
This error happens inside `bme680_set_oversampling_rates()` when it is called by  `bme680_init_sensor()` because the `i2c_dev` is already locked by the calling method.

Appreciate you look into this issue and many thanks for the great efforts.

**Comment by UncleRus** [comment]
Thank you for reporting this bug!
