### ISSUE TITLE
esp32 cam + adc mic+12c lcd comunication with esp32 +spi tft + i2s speaker+servo motor 

### ISSUE THREAD

**Issue by hiibrarahmad** [UncleRus/esp-idf-lib#521]
### The issue

hello sir currently working on my project and trying a lot of different approaches as I am not quite a good programmer and I just pick and try to figure out how to attach 
in this project
on the server side, I have esp32 which has two push button tft display the speaker, first, it connects through websocket, and when the client esp32cam press the button it sends a pic to the server esp32 and show it on tft display, and from the server when push button so servo motor connect on client rotate and when another pus button pressed on the client it should i start audio from client and broadcast on server speaker and the second push button on server side i am using for switching case

here is the client-side repo
https://github.com/hiibrarahmad/esp32cam_max9814_servomotor
here is the server-side repo
https://github.com/hiibrarahmad/esp32_max98357A_tft

the main thing is an issue i am facing is 

![Screenshot 2023-05-29 225220](https://github.com/UncleRus/esp-idf-lib/assets/46841978/7768268b-3262-495c-8c3d-3b355b0648f9)
please fix it I my whole subject is at stake and I will appreciate you so much 

### Which SDK are you using?

esp-idf

### Which version of SDK are you using?

a

### Which build target have you used?

- [X] esp32
- [X] esp32s2
- [ ] esp32s3
- [ ] esp32c2
- [ ] esp8266
- [ ] other

### Component causing the issue

audio

### Anything in the logs that might be useful for us?

```console
i got different issue 

abort() was called at PC 0x4014598f on core 1


assert failed: pbuf_free IDF/components/lwip/lwip/src/core/pbuf.c:757 (pbuf_free: p->ref > 0)

E (13184) task_wdt: Task watchdog got triggered. The following tasks did not reset the watchdog in time: E (13184) task_wdt: - IDLE (CPU 0) E (13184) task_wdt: Tasks currently running: E (13184) task_wdt: CPU 0: audio task E (13184) task_wdt: CPU 1: loopTask E (13184) task_wdt: Aborting.
```

### Additional information or context

I give different to try with the help of chat gpt but still, i don't know why sometimes it works just for a while and i got the error

### Confirmation

- [X] This report is not a question nor a request for drivers.

**Comment by trombik** [comment]
Our components do not include "audio". Please ask someone else. Thank you.
