### ISSUE TITLE
Support for Sensirion STS3X

### ISSUE THREAD

**Issue by slimcdk** [UncleRus/esp-idf-lib#531]
### Device name

STS3X

### Device description

Device is a digital temperature sensor. It communicates using I2C.

### Device product page URL

https://www.sensirion.com/search/products?q=STS3x

### Datasheet URL

https://www.sensirion.com/media/documents/1C706A20/6164200F/Sensirion_Temperature_Sensors_STS3xA_Datasheet.pdf

### Can the device be purchased at any of the followings?

- [ ] AliExpress
- [ ] Amazon
- [ ] ebay
- [ ] Digi-Key
- [X] Mouser

### URLs to purchase the device

https://eu.mouser.com/c/sensors/temperature-sensors/board-mount-temperature-sensors/?m=Sensirion&series=STS3x-DIS

**Comment by slimcdk** [comment]
Pull request opened #532

**Comment by UncleRus** [comment]
Thank you!

**Comment by UncleRus** [comment]
Hmm... Did you check your PR on real device?
The datasheet says that the raw data size is 3 bytes. And in your code, the raw data size is 6 bytes.

![изображение](https://github.com/UncleRus/esp-idf-lib/assets/533006/aea8ab73-e008-4e15-b761-5b2983f84888)

```C
#define STS3X_RAW_DATA_SIZE 6

typedef uint8_t sts3x_raw_data_t[STS3X_RAW_DATA_SIZE];
```

**Comment by UncleRus** [comment]
I'm rolling back the merge of your PR until I get confirmation that the driver works with the actual device.

**Comment by slimcdk** [comment]
Sorry for the radio silence! Still have a bit of vacation left, so I'll explain what I have currently tested. You are right, that the size is only 3 bytes due to the lack of humidity compared to the SHT (which this implementation is an exact copy off). I have tested the driver with an ESP32-S3 and STS31 at 100 MHz and didn't encounter any issues for the week I have been using it.

I'll adjust the size allocation next week and test before submitting a new PR.

**Comment by slimcdk** [comment]
@UncleRus I have verified that the smaller allocation works.

**Comment by slimcdk** [comment]
Had some conflicts with the files were added and then removed from upstream, so I couldn't figure out to sync properly, so I made a new branch.

Driver is tested on real hardware and is reporting correct measurements.
