### ISSUE TITLE
Wiegand callback returning zeros

### ISSUE THREAD

**Issue by drmendoz** [UncleRus/esp-idf-lib#535]
### The issue

I am using a Wiegand reader and my hardware implementation is working in ESP8266 but in ESP32 is not working and get a infinite loop of zeros value and not getting the card data.

### Confirmation

- [X] This report is not a bug report in code, a question, nor a request for drivers.

**Comment by UncleRus** [comment]
1. No context was provided.
2. I just tested the wiegand library on real hardware and it works great.

I am closing this issue.
