### ISSUE TITLE
Library imported correctly but esp32 is restarting.

### ISSUE THREAD

**Issue by ravishree19** [UncleRus/esp-idf-lib#61]
**Devcie type**
- ESP32
**Framework version**
-  ESP-IDF latest master
I have to interface dht22 sensor in ESP32 using esp-idf.I refered https://github.com/UncleRus/esp-idf-lib for dht22 and i was unable to include the dht lib.Can you please help me with the CmakeList.txt file and the Make file to include path.The issue after following the procedure in above link is that esp32 is restarting.I didnt know how CmakeList file works.
Screenshot of the errors after flashing the code in it.
![1](https://user-images.githubusercontent.com/59655089/72044722-90b10100-32da-11ea-9e7d-602fd1f48de7.png)
![2](https://user-images.githubusercontent.com/59655089/72044730-93135b00-32da-11ea-80e9-5ae70131162c.png)
![3](https://user-images.githubusercontent.com/59655089/72044734-9575b500-32da-11ea-8ecf-9a42952422bd.png)

**Comment by XxKavosxX** [comment]
Yes, the same to me

**Comment by zmnv** [comment]
Have the same trouble.
I use 'dht' from esp-idf-lib last master from now.
Also 'esp-idf' last for now.
Trying to use DH11 (DHT_TYPE_DHT11 and others). Also my sensor is not connected))

**Comment by JoaoGarrido** [comment]
Had the same issue and solved it doing the following:
On the dht.c file do the following change:
```c
#define CHECK_LOGE(x, msg, ...) do { \
        esp_err_t __; \
        if ((__ = x) != ESP_OK) { \
            PORT_EXIT_CRITICAL; \
            ESP_LOGE(TAG, msg, ## __VA_ARGS__); \
            return __; \
        } \
    } while (0)
```
