### ISSUE TITLE
MCP23S17 SPI driver is broken (device addressing is wrong, R/W bit is missing)

### ISSUE THREAD

**Issue by fri-sch** [UncleRus/esp-idf-lib#64]
**Devcie type**
- [x] ESP32
- [x] ESP8226

**Framework version**
- [x] ESP-IDF latest master
- [x] ESP-IDF 3.2.2
- [x] ESP8266 RTOS SDK latest master
- [x] ESP8266 RTOS SDK 3.2

**Describe the bug**
The driver for the MCP23S17 doesn't work because the device address in the first byte of the SPI transfer is wrong. For further information see the fix here: #63.

**Comment by UncleRus** [comment]
Just merged your fix.
Thank you!
