### ISSUE TITLE
CCS811B 

### ISSUE THREAD

**Issue by digimatt22** [UncleRus/esp-idf-lib#66]
Is anyone working on porting the CCS811B driver over from esp-open-rtos?  If not I may attempt in the near future and submit a PR as I will need it in an upcoming project. Great library!

**Comment by UncleRus** [comment]
> I may attempt in the near future and submit a PR
That's would be great!

**Comment by UncleRus** [comment]
I've ported this driver, see #67
Could you test it?

**Comment by digimatt22** [comment]
Absolutely but it will be a few day as I am traveling to a conference.  Will have access to the hardware again on Friday.

**Comment by digimatt22** [comment]
I have begun testing the driver and found the following items.   I will continue to work through them but wanted to give an update.  

ccs811_init_desc -> port and addr are flipped compared to other libraries.  I have changed their order to stay consistent with other implementations

ccs811_init_sensor -> within this function there is a write of no data to a specific register (CCS811_REG_APP_START) the i2c_dev_write_reg does not allow for this.  I can disable this check but all future calls appear to fail once I have.  I will continue to look into this, if you have seen this before and have devised a solution please let me know.

**Comment by UncleRus** [comment]
I updated PR according to your comments

**Comment by UncleRus** [comment]
@digimatt22 Any news on testing?

**Comment by digimatt22** [comment]
Testing is paused right now as I wait for a new logic analyzer to arrive so I can see what’s going on vs guess. It arrives later this week.

**Comment by UncleRus** [comment]
I'm going to merge this driver as it is in humble hope that someone will someday try to use it and be kind enough to create an issue in this repository if something goes wrong.

**Comment by trombik** [comment]
I'm fine with it. I ordered a breakout module a week ago, to be delivered in another week or two.
