### ISSUE TITLE
Second local declaration for res value.

### ISSUE THREAD

**Issue by marbalon** [UncleRus/esp-idf-lib#8]
Here is a bug in this function. Function returns ESP_OK in case of i2c_master_cmd_begin returns ESP_FAIL because it is stored in local res value.

https://github.com/UncleRus/esp-idf-lib/blob/125dbb3a81e325ca3d28f2ead57c2c943253dec6/components/i2cdev/i2cdev.c#L201

**Comment by UncleRus** [comment]
Nice catch!
