### ISSUE TITLE
New feature: VS1053 support

### ISSUE THREAD

**Issue by h1aji** [UncleRus/esp-idf-lib#83]
**Device type**
- [x] ESP8226

**Framework version**
- [x] ESP8266 RTOS SDK latest master
- [x] ESP8266 RTOS SDK 3.2

**Describe the bug**
Is there any chance you could add support for VS1053 board?

**Comment by nopnop2002** [comment]
This may be helpful:

https://github.com/nopnop2002/esp-idf-vs1053

**Comment by h1aji** [comment]
@UncleRus  this version does not support esp8266 board
