### ISSUE TITLE
Enhancement: PCF8574/Pull-up

### ISSUE THREAD

**Issue by wkorn** [UncleRus/esp-idf-lib#87]
**Device type**
- [x] ESP32
- [x] ESP8226

**Framework version**
- [x] ESP-IDF latest master
- [x] ESP8266 RTOS SDK latest master

Certain PCF8574 based IO expanders seem to work with ESP internal pull-ups disabled while others do not. I tested the hd44780_i2c example with various displays. With internal pull-ups disabled some displays simply did not show anything and the application failed with an error indicating that write to device at address 0x27 failed (line 57). Generally enabling the ESP internal pull-ups made all displays work. 

So I applied the following change to pcf8574.c generally enabling the internal pull-ups.
[pcf8574.txt](https://github.com/UncleRus/esp-idf-lib/files/4740164/pcf8574.txt)

Another option would be giving explicit control over the pull-up settings by adding parameters to pcf8574_init_desc.

**Comment by UncleRus** [comment]
It's better not to do it this way, since pull-up can be configured before calling `pcf8574_init_desc()`.
```C
...
memset(&pcf8574, 0, sizeof(i2c_dev_t));
pcf8574.cfg.sda_pullup_en = GPIO_PULLUP_ENABLE;
pcf8574.cfg.scl_pullup_en = GPIO_PULLUP_ENABLE;
ESP_ERROR_CHECK(pcf8574_init_desc(&pcf8574, 0, I2C_ADDR, SDA_GPIO, SCL_GPIO));
...
```
