### ISSUE TITLE
Can't add the components - fatal error: hd44780.h: No such file or directory

### ISSUE THREAD

**Issue by vlaskz** [UncleRus/esp-idf-lib#93]
I'm trying to add the components as described in the readme.md:
```
CMAKELISTS:

set(COMPONENT_SRCS "hello_world_main.c")
set(COMPONENT_ADD_INCLUDEDIRS "")
set(EXTRA_COMPONENT_DIRS /~/esp/esp-idf-lib/components)
register_component()



MAKEFILE:

PROJECT_NAME := hello-world
EXTRA_COMPONENT_DIRS := /~/esp/esp-idf-lib/components
include $(IDF_PATH)/make/project.mk


```
![Screenshot from 2020-07-05 23-06-43](https://user-images.githubusercontent.com/14188407/86548843-3d7bdc00-bf14-11ea-8698-73e415c8135a.png)

and my components folder is in: ~/esp/esp-idf-lib/components:

![Screenshot from 2020-07-05 23-08-28](https://user-images.githubusercontent.com/14188407/86548951-9481b100-bf14-11ea-8159-2c3850a76837.png)

but, when i do  `make flash` all i receive is: `fatal error: hd44780.h: No such file or directory`

**Comment by UncleRus** [comment]
Wrong path in `EXTRA_COMPONENTS_DIR`.
Please use full path like this:
`EXTRA_COMPONENTS_DIR = /home/<username>/esp/esp-idf-lib/components`

**Comment by vlaskz** [comment]
thank you, Mr. You're awesome.

**Comment by vlaskz** [comment]
Hello Mr. i would appreciate your help one more time.  I just tested the solution you've provided now, and it doesn't work. It still showing 'no such file or directory' error.
