### ISSUE TITLE
Generic application multi-sensor 

### ISSUE THREAD

**Issue by SERIDJ** [UncleRus/esp-idf-lib#98]
hi,

i am working on application multi-sensor using esp-idf-lib so i connect all my sensor with mux TCA9548A and i want to now if i need to create instance i2c_dev_t dev  for each sensor or i can use one for all same sensor ?

**Comment by UncleRus** [comment]
Hi! You need separate descriptors for each i2c device.

**Comment by SERIDJ** [comment]
@UncleRus  oky so i work with detected device so i can create instance with malloc bcs number of device is detected with i2ccannser 

now i create max : 


/***************************************************/
static float pressure, temperature, humidity;
static bmp280_t            dev_bme280 [8]  =  {0};
static bmp280_params_t params_bme280  [8]   = {0};
/****************************************************/
uint16_t lux;
i2c_dev_t dev_bh1750[8]=  {0};
/****************************************************/
i2c_dev_t dev_pcf8574[8];
uint16_t read_port_pcf8574;

/****************************************************/

**Comment by UncleRus** [comment]
Yes you can create device descriptors dynamically, e.g.
```C
i2c_dev_t *bh1750; // pointer to device descriptor

...

bh1750 = malloc(sizeof(i2c_dev_t)); // allocate memory for descriptor
memset(bh1750, 0, sizeof(i2c_dev_t))); // fill it with zeroes

... // init descriptor, init device, use it

free(bh1750); // free allocated memory
```

**Comment by SERIDJ** [comment]
Ah yes yes but for sensor i don't think I free memory bcs I use all time read_bh1750 and I don't initialize device for each read 

So it's don't give problem if I don't use free(p) ?
