### ISSUE TITLE
can't use esp-idf-lib in my projetcs

### ISSUE THREAD

**Issue by aledoors** [UncleRus/esp-idf-lib#99]
**Device type**
- [x] ESP32-SOLO-1
and it is configured to one core

**Framework version**
- [x] ESP-IDF latest master

**Describe the bug**
i got the followind in the terminal 👍 

ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:6808
load:0x40078000,len:14076
load:0x40080400,len:4304
entry 0x400806e8
I (71) boot: Chip Revision: 1
I (71) boot_comm: chip revision: 1, min. bootloader chip revision: 0
I (39) boot: ESP-IDF v4.0.1-dirty 2nd stage bootloader
I (39) boot: compile time 21:37:01
I (40) boot: Enabling RNG early entropy source...
I (45) boot: SPI Speed      : 40MHz
I (49) boot: SPI Mode       : DIO
I (53) boot: SPI Flash Size : 2MB
I (57) boot: Partition Table:
I (61) boot: ## Label            Usage          Type ST Offset   Length
I (68) boot:  0 nvs              WiFi data        01 02 00009000 00006000
I (75) boot:  1 phy_init         RF data          01 01 0000f000 00001000
I (83) boot:  2 factory          factory app      00 00 00010000 00100000
I (90) boot: End of partition table
I (94) boot_comm: chip revision: 1, min. application chip revision: 0
I (102) esp_image: segment 0: paddr=0x00010020 vaddr=0x3f400020 size=0x05444 ( 21572) map
I (118) esp_image: segment 1: paddr=0x0001546c vaddr=0x3ffb0000 size=0x018d4 (  6356) load
I (122) esp_image: segment 2: paddr=0x00016d48 vaddr=0x40080000 size=0x00400 (  1024) load
I (129) esp_image: segment 3: paddr=0x00017150 vaddr=0x40080400 size=0x08ec0 ( 36544) load
I (153) esp_image: segment 4: paddr=0x00020018 vaddr=0x400d0018 size=0x14ef8 ( 85752) map
5752) map
I (184) esp_image: segment 5: paddr=0x00034f18 vaddr=0x400892c0 size=0x01258 (  4696) load
I (192) boot: Loaded app from partition at offset 0x10000
I (192) boot: Disabling RNG early entropy source...
I (193) cpu_start: Pro cpu up.
I (197) cpu_start: Application information:
I (202) cpu_start: Project name:     example-bmp280
I (207) cpu_start: App version:      1
I (211) cpu_start: Compile time:     Jul 22 2020 22:54:47
I (218) cpu_start: ELF file SHA256:  cf4cf802a345d069...
I (224) cpu_start: ESP-IDF:          v4.0.1-dirty
I (229) cpu_start: Single core mode
I (233) heap_init: Initializing. RAM available for dynamic allocation:
I (240) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM
I (246) heap_init: At 3FFB2840 len 0002D7C0 (181 KiB): DRAM
I (253) heap_init: At 3FFE0440 len 0001FBC0 (126 KiB): D/IRAM
I (259) heap_init: At 40078000 len 00008000 (32 KiB): IRAM
I (265) heap_init: At 4008A518 len 00015AE8 (86 KiB): IRAM
I (271) cpu_start: Pro cpu start user code
I (289) spi_flash: detected chip: gd
I (289) spi_flash: flash io: dio
W (290) spi_flash: Detected size(4096k) larger than the size in the binary image header(2048k). Using the size in the binary image header.
I (300) cpu_start: Starting scheduler on PRO CPU.
C:/esp-idf/components/freertos/tasks.c:1069 (prvAddNewTaskToReadyList)- assert failed!
abort() was called at PC 0x4008926e on core 0

ELF file SHA256: cf4cf802a345d069

Backtrace: 0x400856e1:0x3ffb36e0 0x40085a5d:0x3ffb3700 0x4008926e:0x3ffb3720 0x400893d3:0x3ffb3740 0x400d3a0e:0x3ffb3780 0x400d0b70:0x3ffb37b0 0x40087ec5:0x3ffb37d0

**Comment by UncleRus** [comment]
This error occurs here in this part of the freertos code:
```C
	/* Assure that xCoreID is valid or we'll have an out-of-bounds on pxCurrentTCB
	   You will assert here if e.g. you only have one CPU enabled in menuconfig and
	   are trying to start a task on core 1. */
	configASSERT( xCoreID == tskNO_AFFINITY || xCoreID < portNUM_PROCESSORS);
```
Some examples in this repository binds task to the second core. For example:
```C
xTaskCreatePinnedToCore(bme680_test, "bme680_test", configMINIMAL_STACK_SIZE * 8, NULL, 5, NULL, APP_CPU_NUM);
```
Correct your code so that there is no core binding:
```C
xTaskCreate(bme680_test, "bme680_test", configMINIMAL_STACK_SIZE * 8, NULL, 5, NULL);
```
